# Generated by Django 3.1.7 on 2021-03-29 11:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('total_energy', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_protein', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_carbs', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_fats', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('halaal', models.BooleanField(default=False)),
                ('shellfish_free', models.BooleanField(default=False)),
                ('lactose_free', models.BooleanField(default=False)),
            ],
        ),
    ]
