# Generated by Django 3.0.2 on 2021-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='gluten_free',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='halaal',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='lactose_free',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='shellfish_free',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='vegetarian',
        ),
        migrations.AddField(
            model_name='diet',
            name='diets',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='diet',
            name='exclude_cuisines',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='diet',
            name='exclude_ingredients',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='diet',
            name='intolerances',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
