# Generated by Django 3.0.2 on 2021-04-13 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_auto_20210413_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='daily_calories',
            field=models.FloatField(default=1200, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
