# Generated by Django 3.0.2 on 2021-04-19 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0004_diet_daily_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='daily_calories',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
