# Generated by Django 3.0.2 on 2021-05-16 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progress_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='current_height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='progress',
            name='current_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)]),
        ),
    ]
