# Generated by Django 3.1.7 on 2021-03-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210329_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
