# Generated by Django 3.0.2 on 2021-04-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='gluten_free',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='halaal',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='lactose_free',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='shellfish_free',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='vegetarian',
        ),
    ]
