# Generated by Django 3.0.2 on 2021-04-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210407_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
