# Generated by Django 3.0.2 on 2021-04-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210413_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='prep_time',
        ),
    ]
