# Generated by Django 3.0.2 on 2021-04-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_prep_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_id',
            new_name='recipe_spoonacuar_id',
        ),
    ]
